// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class AdminPurgePost
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("admin_person_id")]
    [RequiredProperty]
    public long AdminPersonId { get; set; }

    [JsonPropertyName("community_id")]
    [RequiredProperty]
    public long CommunityId { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    [JsonPropertyName("when_")]
    [RequiredProperty]
    public string When { get; set; } = null!;
}
