// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class AdminPurgeCommentView
{
    [JsonPropertyName("admin_purge_comment")]
    [RequiredProperty]
    public AdminPurgeComment AdminPurgeComment { get; set; } = null!;

    [JsonPropertyName("admin")]
    public Person? Admin { get; set; }

    [JsonPropertyName("post")]
    [RequiredProperty]
    public Post Post { get; set; } = null!;
}
