// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class AdminPurgePersonView
{
    [JsonPropertyName("admin_purge_person")]
    [RequiredProperty]
    public AdminPurgePerson AdminPurgePerson { get; set; } = null!;

    [JsonPropertyName("admin")]
    public Person? Admin { get; set; }
}
