// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ApproveRegistrationApplication
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("approve")]
    [RequiredProperty]
    public bool Approve { get; set; }

    [JsonPropertyName("deny_reason")]
    public string? DenyReason { get; set; }
}
