// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class BanPerson
{
    [JsonPropertyName("person_id")]
    [RequiredProperty]
    public long PersonId { get; set; }

    [JsonPropertyName("ban")]
    [RequiredProperty]
    public bool Ban { get; set; }

    [JsonPropertyName("remove_data")]
    public bool? RemoveData { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    [JsonPropertyName("expires")]
    public long? Expires { get; set; }
}
