// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class BlockInstance
{
    [JsonPropertyName("instance_id")]
    [RequiredProperty]
    public long InstanceId { get; set; }

    [JsonPropertyName("block")]
    [RequiredProperty]
    public bool Block { get; set; }
}
