// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CaptchaResponse
{
    [JsonPropertyName("png")]
    [RequiredProperty]
    public string Png { get; set; } = null!;

    [JsonPropertyName("wav")]
    [RequiredProperty]
    public string Wav { get; set; } = null!;

    [JsonPropertyName("uuid")]
    [RequiredProperty]
    public string Uuid { get; set; } = null!;
}
