// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ChangePassword
{
    [JsonPropertyName("new_password")]
    [RequiredProperty]
    public string NewPassword { get; set; } = null!;

    [JsonPropertyName("new_password_verify")]
    [RequiredProperty]
    public string NewPasswordVerify { get; set; } = null!;

    [JsonPropertyName("old_password")]
    [RequiredProperty]
    public string OldPassword { get; set; } = null!;
}
