// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CommunityResponse
{
    [JsonPropertyName("community_view")]
    [RequiredProperty]
    public CommunityView CommunityView { get; set; } = null!;

    [JsonPropertyName("discussion_languages")]
    [RequiredProperty]
    public List<long> DiscussionLanguages { get; set; } = null!;
}
