// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CommentAggregates
{
    [JsonPropertyName("comment_id")]
    [RequiredProperty]
    public long CommentId { get; set; }

    [JsonPropertyName("score")]
    [RequiredProperty]
    public long Score { get; set; }

    [JsonPropertyName("upvotes")]
    [RequiredProperty]
    public long Upvotes { get; set; }

    [JsonPropertyName("downvotes")]
    [RequiredProperty]
    public long Downvotes { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("child_count")]
    [RequiredProperty]
    public long ChildCount { get; set; }
}
