// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CommentReportResponse
{
    [JsonPropertyName("comment_report_view")]
    [RequiredProperty]
    public CommentReportView CommentReportView { get; set; } = null!;
}
