// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CommunityView
{
    [JsonPropertyName("community")]
    [RequiredProperty]
    public Community Community { get; set; } = null!;

    [JsonPropertyName("subscribed")]
    [RequiredProperty]
    public SubscribedType Subscribed { get; set; }

    [JsonPropertyName("blocked")]
    [RequiredProperty]
    public bool Blocked { get; set; }

    [JsonPropertyName("counts")]
    [RequiredProperty]
    public CommunityAggregates Counts { get; set; } = null!;

    [JsonPropertyName("banned_from_community")]
    [RequiredProperty]
    public bool BannedFromCommunity { get; set; }
}
