// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Community
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("name")]
    [RequiredProperty]
    public string Name { get; set; } = null!;

    [JsonPropertyName("title")]
    [RequiredProperty]
    public string Title { get; set; } = null!;

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("removed")]
    [RequiredProperty]
    public bool Removed { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("deleted")]
    [RequiredProperty]
    public bool Deleted { get; set; }

    [JsonPropertyName("nsfw")]
    [RequiredProperty]
    public bool Nsfw { get; set; }

    [JsonPropertyName("actor_id")]
    [RequiredProperty]
    public string ActorId { get; set; } = null!;

    [JsonPropertyName("local")]
    [RequiredProperty]
    public bool Local { get; set; }

    [JsonPropertyName("icon")]
    public string? Icon { get; set; }

    [JsonPropertyName("banner")]
    public string? Banner { get; set; }

    [JsonPropertyName("hidden")]
    [RequiredProperty]
    public bool Hidden { get; set; }

    [JsonPropertyName("posting_restricted_to_mods")]
    [RequiredProperty]
    public bool PostingRestrictedToMods { get; set; }

    [JsonPropertyName("instance_id")]
    [RequiredProperty]
    public long InstanceId { get; set; }

    [JsonPropertyName("visibility")]
    [RequiredProperty]
    public CommunityVisibility Visibility { get; set; }
}
