// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CommentResponse
{
    [JsonPropertyName("comment_view")]
    [RequiredProperty]
    public CommentView CommentView { get; set; } = null!;

    [JsonPropertyName("recipient_ids")]
    [RequiredProperty]
    public List<long> RecipientIds { get; set; } = null!;
}
