// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CommunityVisibility
{
    [JsonStringEnumMemberName("Public")]
    Public,

    [JsonStringEnumMemberName("LocalOnly")]
    LocalOnly
}
