// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CreateSite
{
    [JsonPropertyName("name")]
    [RequiredProperty]
    public string Name { get; set; } = null!;

    [JsonPropertyName("sidebar")]
    public string? Sidebar { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("icon")]
    public string? Icon { get; set; }

    [JsonPropertyName("banner")]
    public string? Banner { get; set; }

    [JsonPropertyName("enable_downvotes")]
    public bool? EnableDownvotes { get; set; }

    [JsonPropertyName("enable_nsfw")]
    public bool? EnableNsfw { get; set; }

    [JsonPropertyName("community_creation_admin_only")]
    public bool? CommunityCreationAdminOnly { get; set; }

    [JsonPropertyName("require_email_verification")]
    public bool? RequireEmailVerification { get; set; }

    [JsonPropertyName("application_question")]
    public string? ApplicationQuestion { get; set; }

    [JsonPropertyName("private_instance")]
    public bool? PrivateInstance { get; set; }

    [JsonPropertyName("default_theme")]
    public string? DefaultTheme { get; set; }

    [JsonPropertyName("default_post_listing_type")]
    public ListingType? DefaultPostListingType { get; set; }

    [JsonPropertyName("default_sort_type")]
    public SortType? DefaultSortType { get; set; }

    [JsonPropertyName("legal_information")]
    public string? LegalInformation { get; set; }

    [JsonPropertyName("application_email_admins")]
    public bool? ApplicationEmailAdmins { get; set; }

    [JsonPropertyName("hide_modlog_mod_names")]
    public bool? HideModlogModNames { get; set; }

    [JsonPropertyName("discussion_languages")]
    public List<long>? DiscussionLanguages { get; set; }

    [JsonPropertyName("slur_filter_regex")]
    public string? SlurFilterRegex { get; set; }

    [JsonPropertyName("actor_name_max_length")]
    public long? ActorNameMaxLength { get; set; }

    [JsonPropertyName("rate_limit_message")]
    public long? RateLimitMessage { get; set; }

    [JsonPropertyName("rate_limit_message_per_second")]
    public long? RateLimitMessagePerSecond { get; set; }

    [JsonPropertyName("rate_limit_post")]
    public long? RateLimitPost { get; set; }

    [JsonPropertyName("rate_limit_post_per_second")]
    public long? RateLimitPostPerSecond { get; set; }

    [JsonPropertyName("rate_limit_register")]
    public long? RateLimitRegister { get; set; }

    [JsonPropertyName("rate_limit_register_per_second")]
    public long? RateLimitRegisterPerSecond { get; set; }

    [JsonPropertyName("rate_limit_image")]
    public long? RateLimitImage { get; set; }

    [JsonPropertyName("rate_limit_image_per_second")]
    public long? RateLimitImagePerSecond { get; set; }

    [JsonPropertyName("rate_limit_comment")]
    public long? RateLimitComment { get; set; }

    [JsonPropertyName("rate_limit_comment_per_second")]
    public long? RateLimitCommentPerSecond { get; set; }

    [JsonPropertyName("rate_limit_search")]
    public long? RateLimitSearch { get; set; }

    [JsonPropertyName("rate_limit_search_per_second")]
    public long? RateLimitSearchPerSecond { get; set; }

    [JsonPropertyName("federation_enabled")]
    public bool? FederationEnabled { get; set; }

    [JsonPropertyName("federation_debug")]
    public bool? FederationDebug { get; set; }

    [JsonPropertyName("captcha_enabled")]
    public bool? CaptchaEnabled { get; set; }

    [JsonPropertyName("captcha_difficulty")]
    public string? CaptchaDifficulty { get; set; }

    [JsonPropertyName("allowed_instances")]
    public List<string>? AllowedInstances { get; set; }

    [JsonPropertyName("blocked_instances")]
    public List<string>? BlockedInstances { get; set; }

    [JsonPropertyName("taglines")]
    public List<string>? Taglines { get; set; }

    [JsonPropertyName("registration_mode")]
    public RegistrationMode? RegistrationMode { get; set; }

    [JsonPropertyName("content_warning")]
    public string? ContentWarning { get; set; }

    [JsonPropertyName("default_post_listing_mode")]
    public PostListingMode? DefaultPostListingMode { get; set; }
}
