// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CreateComment
{
    [JsonPropertyName("content")]
    [RequiredProperty]
    public string Content { get; set; } = null!;

    [JsonPropertyName("post_id")]
    [RequiredProperty]
    public long PostId { get; set; }

    [JsonPropertyName("parent_id")]
    public long? ParentId { get; set; }

    [JsonPropertyName("language_id")]
    public long? LanguageId { get; set; }
}
