// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CreateCommentReport
{
    [JsonPropertyName("comment_id")]
    [RequiredProperty]
    public long CommentId { get; set; }

    [JsonPropertyName("reason")]
    [RequiredProperty]
    public string Reason { get; set; } = null!;
}
