// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CustomEmoji
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("local_site_id")]
    [RequiredProperty]
    public long LocalSiteId { get; set; }

    [JsonPropertyName("shortcode")]
    [RequiredProperty]
    public string Shortcode { get; set; } = null!;

    [JsonPropertyName("image_url")]
    [RequiredProperty]
    public string ImageUrl { get; set; } = null!;

    [JsonPropertyName("alt_text")]
    [RequiredProperty]
    public string AltText { get; set; } = null!;

    [JsonPropertyName("category")]
    [RequiredProperty]
    public string Category { get; set; } = null!;

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }
}
