// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class CustomEmojiView
{
    [JsonPropertyName("custom_emoji")]
    [RequiredProperty]
    public CustomEmoji CustomEmoji { get; set; } = null!;

    [JsonPropertyName("keywords")]
    [RequiredProperty]
    public List<CustomEmojiKeyword> Keywords { get; set; } = null!;
}
