// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class DeleteCommunity
{
    [JsonPropertyName("community_id")]
    [RequiredProperty]
    public long CommunityId { get; set; }

    [JsonPropertyName("deleted")]
    [RequiredProperty]
    public bool Deleted { get; set; }
}
