// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class DistinguishComment
{
    [JsonPropertyName("comment_id")]
    [RequiredProperty]
    public long CommentId { get; set; }

    [JsonPropertyName("distinguished")]
    [RequiredProperty]
    public bool Distinguished { get; set; }
}
