// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class EditCommunity
{
    [JsonPropertyName("community_id")]
    [RequiredProperty]
    public long CommunityId { get; set; }

    [JsonPropertyName("title")]
    public string? Title { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("icon")]
    public string? Icon { get; set; }

    [JsonPropertyName("banner")]
    public string? Banner { get; set; }

    [JsonPropertyName("nsfw")]
    public bool? Nsfw { get; set; }

    [JsonPropertyName("posting_restricted_to_mods")]
    public bool? PostingRestrictedToMods { get; set; }

    [JsonPropertyName("discussion_languages")]
    public List<long>? DiscussionLanguages { get; set; }

    [JsonPropertyName("visibility")]
    public CommunityVisibility? Visibility { get; set; }
}
