// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class EditPrivateMessage
{
    [JsonPropertyName("private_message_id")]
    [RequiredProperty]
    public long PrivateMessageId { get; set; }

    [JsonPropertyName("content")]
    [RequiredProperty]
    public string Content { get; set; } = null!;
}
