// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class EditPost
{
    [JsonPropertyName("post_id")]
    [RequiredProperty]
    public long PostId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("body")]
    public string? Body { get; set; }

    [JsonPropertyName("alt_text")]
    public string? AltText { get; set; }

    [JsonPropertyName("nsfw")]
    public bool? Nsfw { get; set; }

    [JsonPropertyName("language_id")]
    public long? LanguageId { get; set; }

    [JsonPropertyName("custom_thumbnail")]
    public string? CustomThumbnail { get; set; }
}
