// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class FeaturePost
{
    [JsonPropertyName("post_id")]
    [RequiredProperty]
    public long PostId { get; set; }

    [JsonPropertyName("featured")]
    [RequiredProperty]
    public bool Featured { get; set; }

    [JsonPropertyName("feature_type")]
    [RequiredProperty]
    public PostFeatureType FeatureType { get; set; }
}
