// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class FederatedInstances
{
    [JsonPropertyName("linked")]
    [RequiredProperty]
    public List<InstanceWithFederationState> Linked { get; set; } = null!;

    [JsonPropertyName("allowed")]
    [RequiredProperty]
    public List<InstanceWithFederationState> Allowed { get; set; } = null!;

    [JsonPropertyName("blocked")]
    [RequiredProperty]
    public List<InstanceWithFederationState> Blocked { get; set; } = null!;
}
