// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetCommunityResponse
{
    [JsonPropertyName("community_view")]
    [RequiredProperty]
    public CommunityView CommunityView { get; set; } = null!;

    [JsonPropertyName("site")]
    public Site? Site { get; set; }

    [JsonPropertyName("moderators")]
    [RequiredProperty]
    public List<CommunityModeratorView> Moderators { get; set; } = null!;

    [JsonPropertyName("discussion_languages")]
    [RequiredProperty]
    public List<long> DiscussionLanguages { get; set; } = null!;
}
