// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetModlogResponse
{
    [JsonPropertyName("removed_posts")]
    [RequiredProperty]
    public List<ModRemovePostView> RemovedPosts { get; set; } = null!;

    [JsonPropertyName("locked_posts")]
    [RequiredProperty]
    public List<ModLockPostView> LockedPosts { get; set; } = null!;

    [JsonPropertyName("featured_posts")]
    [RequiredProperty]
    public List<ModFeaturePostView> FeaturedPosts { get; set; } = null!;

    [JsonPropertyName("removed_comments")]
    [RequiredProperty]
    public List<ModRemoveCommentView> RemovedComments { get; set; } = null!;

    [JsonPropertyName("removed_communities")]
    [RequiredProperty]
    public List<ModRemoveCommunityView> RemovedCommunities { get; set; } = null!;

    [JsonPropertyName("banned_from_community")]
    [RequiredProperty]
    public List<ModBanFromCommunityView> BannedFromCommunity { get; set; } = null!;

    [JsonPropertyName("banned")]
    [RequiredProperty]
    public List<ModBanView> Banned { get; set; } = null!;

    [JsonPropertyName("added_to_community")]
    [RequiredProperty]
    public List<ModAddCommunityView> AddedToCommunity { get; set; } = null!;

    [JsonPropertyName("transferred_to_community")]
    [RequiredProperty]
    public List<ModTransferCommunityView> TransferredToCommunity { get; set; } = null!;

    [JsonPropertyName("added")]
    [RequiredProperty]
    public List<ModAddView> Added { get; set; } = null!;

    [JsonPropertyName("admin_purged_persons")]
    [RequiredProperty]
    public List<AdminPurgePersonView> AdminPurgedPersons { get; set; } = null!;

    [JsonPropertyName("admin_purged_communities")]
    [RequiredProperty]
    public List<AdminPurgeCommunityView> AdminPurgedCommunities { get; set; } = null!;

    [JsonPropertyName("admin_purged_posts")]
    [RequiredProperty]
    public List<AdminPurgePostView> AdminPurgedPosts { get; set; } = null!;

    [JsonPropertyName("admin_purged_comments")]
    [RequiredProperty]
    public List<AdminPurgeCommentView> AdminPurgedComments { get; set; } = null!;

    [JsonPropertyName("hidden_communities")]
    [RequiredProperty]
    public List<ModHideCommunityView> HiddenCommunities { get; set; } = null!;
}
