// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetPersonDetailsResponse
{
    [JsonPropertyName("person_view")]
    [RequiredProperty]
    public PersonView PersonView { get; set; } = null!;

    [JsonPropertyName("site")]
    public Site? Site { get; set; }

    [JsonPropertyName("comments")]
    [RequiredProperty]
    public List<CommentView> Comments { get; set; } = null!;

    [JsonPropertyName("posts")]
    [RequiredProperty]
    public List<PostView> Posts { get; set; } = null!;

    [JsonPropertyName("moderates")]
    [RequiredProperty]
    public List<CommunityModeratorView> Moderates { get; set; } = null!;
}
