// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetPersonDetails : IPaginatedResult
{
    [JsonPropertyName("person_id")]
    public long? PersonId { get; set; }

    [JsonPropertyName("username")]
    public string? Username { get; set; }

    [JsonPropertyName("sort")]
    public SortType? Sort { get; set; }

    [JsonPropertyName("page")]
    public long? Page { get; set; }

    [JsonPropertyName("limit")]
    public long? Limit { get; set; }

    [JsonPropertyName("community_id")]
    public long? CommunityId { get; set; }

    [JsonPropertyName("saved_only")]
    public bool? SavedOnly { get; set; }
}
