// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetPosts : IPaginatedResult
{
    [JsonPropertyName("type_")]
    public ListingType? Type { get; set; }

    [JsonPropertyName("sort")]
    public SortType? Sort { get; set; }

    [JsonPropertyName("page")]
    public long? Page { get; set; }

    [JsonPropertyName("limit")]
    public long? Limit { get; set; }

    [JsonPropertyName("community_id")]
    public long? CommunityId { get; set; }

    [JsonPropertyName("community_name")]
    public string? CommunityName { get; set; }

    [JsonPropertyName("saved_only")]
    public bool? SavedOnly { get; set; }

    [JsonPropertyName("liked_only")]
    public bool? LikedOnly { get; set; }

    [JsonPropertyName("disliked_only")]
    public bool? DislikedOnly { get; set; }

    [JsonPropertyName("show_hidden")]
    public bool? ShowHidden { get; set; }

    [JsonPropertyName("show_read")]
    public bool? ShowRead { get; set; }

    [JsonPropertyName("show_nsfw")]
    public bool? ShowNsfw { get; set; }

    [JsonPropertyName("page_cursor")]
    public string? PageCursor { get; set; }
}
