// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetPostsResponse
{
    [JsonPropertyName("posts")]
    [RequiredProperty]
    public List<PostView> Posts { get; set; } = null!;

    [JsonPropertyName("next_page")]
    public string? NextPage { get; set; }
}
