// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetPostResponse
{
    [JsonPropertyName("post_view")]
    [RequiredProperty]
    public PostView PostView { get; set; } = null!;

    [JsonPropertyName("community_view")]
    [RequiredProperty]
    public CommunityView CommunityView { get; set; } = null!;

    [JsonPropertyName("moderators")]
    [RequiredProperty]
    public List<CommunityModeratorView> Moderators { get; set; } = null!;

    [JsonPropertyName("cross_posts")]
    [RequiredProperty]
    public List<PostView> CrossPosts { get; set; } = null!;
}
