// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetReportCountResponse
{
    [JsonPropertyName("community_id")]
    public long? CommunityId { get; set; }

    [JsonPropertyName("comment_reports")]
    [RequiredProperty]
    public long CommentReports { get; set; }

    [JsonPropertyName("post_reports")]
    [RequiredProperty]
    public long PostReports { get; set; }

    [JsonPropertyName("private_message_reports")]
    public long? PrivateMessageReports { get; set; }
}
