// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetSiteResponse
{
    [JsonPropertyName("site_view")]
    [RequiredProperty]
    public SiteView SiteView { get; set; } = null!;

    [JsonPropertyName("admins")]
    [RequiredProperty]
    public List<PersonView> Admins { get; set; } = null!;

    [JsonPropertyName("version")]
    [RequiredProperty]
    public string Version { get; set; } = null!;

    [JsonPropertyName("my_user")]
    public MyUserInfo? MyUser { get; set; }

    [JsonPropertyName("all_languages")]
    [RequiredProperty]
    public List<Language> AllLanguages { get; set; } = null!;

    [JsonPropertyName("discussion_languages")]
    [RequiredProperty]
    public List<long> DiscussionLanguages { get; set; } = null!;

    [JsonPropertyName("taglines")]
    [RequiredProperty]
    public List<Tagline> Taglines { get; set; } = null!;

    [JsonPropertyName("custom_emojis")]
    [RequiredProperty]
    public List<CustomEmojiView> CustomEmojis { get; set; } = null!;

    [JsonPropertyName("blocked_urls")]
    [RequiredProperty]
    public List<LocalSiteUrlBlocklist> BlockedUrls { get; set; } = null!;
}
