// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class GetUnreadCountResponse
{
    [JsonPropertyName("replies")]
    [RequiredProperty]
    public long Replies { get; set; }

    [JsonPropertyName("mentions")]
    [RequiredProperty]
    public long Mentions { get; set; }

    [JsonPropertyName("private_messages")]
    [RequiredProperty]
    public long PrivateMessages { get; set; }
}
