// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class HidePost
{
    [JsonPropertyName("post_ids")]
    [RequiredProperty]
    public List<long> PostIds { get; set; } = null!;

    [JsonPropertyName("hide")]
    [RequiredProperty]
    public bool Hide { get; set; }
}
