// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ImageDetails
{
    [JsonPropertyName("link")]
    [RequiredProperty]
    public string Link { get; set; } = null!;

    [JsonPropertyName("width")]
    [RequiredProperty]
    public long Width { get; set; }

    [JsonPropertyName("height")]
    [RequiredProperty]
    public long Height { get; set; }

    [JsonPropertyName("content_type")]
    [RequiredProperty]
    public string ContentType { get; set; } = null!;
}
