// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class InstanceBlockView
{
    [JsonPropertyName("person")]
    [RequiredProperty]
    public Person Person { get; set; } = null!;

    [JsonPropertyName("instance")]
    [RequiredProperty]
    public Instance Instance { get; set; } = null!;

    [JsonPropertyName("site")]
    public Site? Site { get; set; }
}
