// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class InstanceWithFederationState
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("domain")]
    [RequiredProperty]
    public string Domain { get; set; } = null!;

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("software")]
    public string? Software { get; set; }

    [JsonPropertyName("version")]
    public string? Version { get; set; }

    [JsonPropertyName("federation_state")]
    public ReadableFederationState? FederationState { get; set; }
}
