// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LemmyErrorType
{
    [JsonStringEnumMemberName("report_reason_required")]
    ReportReasonRequired,

    [JsonStringEnumMemberName("report_too_long")]
    ReportTooLong,

    [JsonStringEnumMemberName("not_a_moderator")]
    NotAModerator,

    [JsonStringEnumMemberName("not_an_admin")]
    NotAnAdmin,

    [JsonStringEnumMemberName("cant_block_yourself")]
    CantBlockYourself,

    [JsonStringEnumMemberName("cant_block_admin")]
    CantBlockAdmin,

    [JsonStringEnumMemberName("couldnt_update_user")]
    CouldntUpdateUser,

    [JsonStringEnumMemberName("passwords_do_not_match")]
    PasswordsDoNotMatch,

    [JsonStringEnumMemberName("email_not_verified")]
    EmailNotVerified,

    [JsonStringEnumMemberName("email_required")]
    EmailRequired,

    [JsonStringEnumMemberName("couldnt_update_comment")]
    CouldntUpdateComment,

    [JsonStringEnumMemberName("couldnt_update_private_message")]
    CouldntUpdatePrivateMessage,

    [JsonStringEnumMemberName("cannot_leave_admin")]
    CannotLeaveAdmin,

    [JsonStringEnumMemberName("no_lines_in_html")]
    NoLinesInHtml,

    [JsonStringEnumMemberName("site_metadata_page_is_not_doctype_html")]
    SiteMetadataPageIsNotDoctypeHtml,

    [JsonStringEnumMemberName("pictrs_response_error")]
    PictrsResponseError,

    [JsonStringEnumMemberName("pictrs_purge_response_error")]
    PictrsPurgeResponseError,

    [JsonStringEnumMemberName("pictrs_caching_disabled")]
    PictrsCachingDisabled,

    [JsonStringEnumMemberName("image_url_missing_path_segments")]
    ImageUrlMissingPathSegments,

    [JsonStringEnumMemberName("image_url_missing_last_path_segment")]
    ImageUrlMissingLastPathSegment,

    [JsonStringEnumMemberName("pictrs_api_key_not_provided")]
    PictrsApiKeyNotProvided,

    [JsonStringEnumMemberName("no_content_type_header")]
    NoContentTypeHeader,

    [JsonStringEnumMemberName("not_an_image_type")]
    NotAnImageType,

    [JsonStringEnumMemberName("not_a_mod_or_admin")]
    NotAModOrAdmin,

    [JsonStringEnumMemberName("no_admins")]
    NoAdmins,

    [JsonStringEnumMemberName("not_top_admin")]
    NotTopAdmin,

    [JsonStringEnumMemberName("not_top_mod")]
    NotTopMod,

    [JsonStringEnumMemberName("not_logged_in")]
    NotLoggedIn,

    [JsonStringEnumMemberName("not_higher_mod")]
    NotHigherMod,

    [JsonStringEnumMemberName("not_higher_admin")]
    NotHigherAdmin,

    [JsonStringEnumMemberName("site_ban")]
    SiteBan,

    [JsonStringEnumMemberName("deleted")]
    Deleted,

    [JsonStringEnumMemberName("banned_from_community")]
    BannedFromCommunity,

    [JsonStringEnumMemberName("couldnt_find_community")]
    CouldntFindCommunity,

    [JsonStringEnumMemberName("couldnt_find_person")]
    CouldntFindPerson,

    [JsonStringEnumMemberName("couldnt_find_comment")]
    CouldntFindComment,

    [JsonStringEnumMemberName("couldnt_find_comment_report")]
    CouldntFindCommentReport,

    [JsonStringEnumMemberName("couldnt_find_post_report")]
    CouldntFindPostReport,

    [JsonStringEnumMemberName("couldnt_find_private_message_report")]
    CouldntFindPrivateMessageReport,

    [JsonStringEnumMemberName("couldnt_find_local_user")]
    CouldntFindLocalUser,

    [JsonStringEnumMemberName("couldnt_find_person_mention")]
    CouldntFindPersonMention,

    [JsonStringEnumMemberName("couldnt_find_registration_application")]
    CouldntFindRegistrationApplication,

    [JsonStringEnumMemberName("couldnt_find_comment_reply")]
    CouldntFindCommentReply,

    [JsonStringEnumMemberName("couldnt_find_private_message")]
    CouldntFindPrivateMessage,

    [JsonStringEnumMemberName("couldnt_find_activity")]
    CouldntFindActivity,

    [JsonStringEnumMemberName("person_is_blocked")]
    PersonIsBlocked,

    [JsonStringEnumMemberName("community_is_blocked")]
    CommunityIsBlocked,

    [JsonStringEnumMemberName("instance_is_blocked")]
    InstanceIsBlocked,

    [JsonStringEnumMemberName("downvotes_are_disabled")]
    DownvotesAreDisabled,

    [JsonStringEnumMemberName("instance_is_private")]
    InstanceIsPrivate,

    [JsonStringEnumMemberName("invalid_password")]
    InvalidPassword,

    [JsonStringEnumMemberName("site_description_length_overflow")]
    SiteDescriptionLengthOverflow,

    [JsonStringEnumMemberName("honeypot_failed")]
    HoneypotFailed,

    [JsonStringEnumMemberName("registration_application_is_pending")]
    RegistrationApplicationIsPending,

    [JsonStringEnumMemberName("cant_enable_private_instance_and_federation_together")]
    CantEnablePrivateInstanceAndFederationTogether,

    [JsonStringEnumMemberName("locked")]
    Locked,

    [JsonStringEnumMemberName("couldnt_create_comment")]
    CouldntCreateComment,

    [JsonStringEnumMemberName("max_comment_depth_reached")]
    MaxCommentDepthReached,

    [JsonStringEnumMemberName("no_comment_edit_allowed")]
    NoCommentEditAllowed,

    [JsonStringEnumMemberName("only_admins_can_create_communities")]
    OnlyAdminsCanCreateCommunities,

    [JsonStringEnumMemberName("community_already_exists")]
    CommunityAlreadyExists,

    [JsonStringEnumMemberName("language_not_allowed")]
    LanguageNotAllowed,

    [JsonStringEnumMemberName("only_mods_can_post_in_community")]
    OnlyModsCanPostInCommunity,

    [JsonStringEnumMemberName("couldnt_update_post")]
    CouldntUpdatePost,

    [JsonStringEnumMemberName("no_post_edit_allowed")]
    NoPostEditAllowed,

    [JsonStringEnumMemberName("couldnt_find_post")]
    CouldntFindPost,

    [JsonStringEnumMemberName("edit_private_message_not_allowed")]
    EditPrivateMessageNotAllowed,

    [JsonStringEnumMemberName("site_already_exists")]
    SiteAlreadyExists,

    [JsonStringEnumMemberName("application_question_required")]
    ApplicationQuestionRequired,

    [JsonStringEnumMemberName("invalid_default_post_listing_type")]
    InvalidDefaultPostListingType,

    [JsonStringEnumMemberName("registration_closed")]
    RegistrationClosed,

    [JsonStringEnumMemberName("registration_application_answer_required")]
    RegistrationApplicationAnswerRequired,

    [JsonStringEnumMemberName("email_already_exists")]
    EmailAlreadyExists,

    [JsonStringEnumMemberName("federation_forbidden_by_strict_allow_list")]
    FederationForbiddenByStrictAllowList,

    [JsonStringEnumMemberName("person_is_banned_from_community")]
    PersonIsBannedFromCommunity,

    [JsonStringEnumMemberName("object_is_not_public")]
    ObjectIsNotPublic,

    [JsonStringEnumMemberName("invalid_community")]
    InvalidCommunity,

    [JsonStringEnumMemberName("cannot_create_post_or_comment_in_deleted_or_removed_community")]
    CannotCreatePostOrCommentInDeletedOrRemovedCommunity,

    [JsonStringEnumMemberName("cannot_receive_page")]
    CannotReceivePage,

    [JsonStringEnumMemberName("new_post_cannot_be_locked")]
    NewPostCannotBeLocked,

    [JsonStringEnumMemberName("only_local_admin_can_remove_community")]
    OnlyLocalAdminCanRemoveCommunity,

    [JsonStringEnumMemberName("only_local_admin_can_restore_community")]
    OnlyLocalAdminCanRestoreCommunity,

    [JsonStringEnumMemberName("no_id_given")]
    NoIdGiven,

    [JsonStringEnumMemberName("incorrect_login")]
    IncorrectLogin,

    [JsonStringEnumMemberName("invalid_query")]
    InvalidQuery,

    [JsonStringEnumMemberName("object_not_local")]
    ObjectNotLocal,

    [JsonStringEnumMemberName("post_is_locked")]
    PostIsLocked,

    [JsonStringEnumMemberName("person_is_banned_from_site")]
    PersonIsBannedFromSite,

    [JsonStringEnumMemberName("invalid_vote_value")]
    InvalidVoteValue,

    [JsonStringEnumMemberName("page_does_not_specify_creator")]
    PageDoesNotSpecifyCreator,

    [JsonStringEnumMemberName("no_email_setup")]
    NoEmailSetup,

    [JsonStringEnumMemberName("local_site_not_setup")]
    LocalSiteNotSetup,

    [JsonStringEnumMemberName("email_smtp_server_needs_a_port")]
    EmailSmtpServerNeedsAPort,

    [JsonStringEnumMemberName("missing_an_email")]
    MissingAnEmail,

    [JsonStringEnumMemberName("rate_limit_error")]
    RateLimitError,

    [JsonStringEnumMemberName("invalid_name")]
    InvalidName,

    [JsonStringEnumMemberName("invalid_display_name")]
    InvalidDisplayName,

    [JsonStringEnumMemberName("invalid_matrix_id")]
    InvalidMatrixId,

    [JsonStringEnumMemberName("invalid_post_title")]
    InvalidPostTitle,

    [JsonStringEnumMemberName("invalid_body_field")]
    InvalidBodyField,

    [JsonStringEnumMemberName("bio_length_overflow")]
    BioLengthOverflow,

    [JsonStringEnumMemberName("alt_text_length_overflow")]
    AltTextLengthOverflow,

    [JsonStringEnumMemberName("missing_totp_token")]
    MissingTotpToken,

    [JsonStringEnumMemberName("missing_totp_secret")]
    MissingTotpSecret,

    [JsonStringEnumMemberName("incorrect_totp_token")]
    IncorrectTotpToken,

    [JsonStringEnumMemberName("couldnt_parse_totp_secret")]
    CouldntParseTotpSecret,

    [JsonStringEnumMemberName("couldnt_generate_totp")]
    CouldntGenerateTotp,

    [JsonStringEnumMemberName("totp_already_enabled")]
    TotpAlreadyEnabled,

    [JsonStringEnumMemberName("couldnt_like_comment")]
    CouldntLikeComment,

    [JsonStringEnumMemberName("couldnt_save_comment")]
    CouldntSaveComment,

    [JsonStringEnumMemberName("couldnt_create_report")]
    CouldntCreateReport,

    [JsonStringEnumMemberName("couldnt_resolve_report")]
    CouldntResolveReport,

    [JsonStringEnumMemberName("community_moderator_already_exists")]
    CommunityModeratorAlreadyExists,

    [JsonStringEnumMemberName("community_user_already_banned")]
    CommunityUserAlreadyBanned,

    [JsonStringEnumMemberName("community_block_already_exists")]
    CommunityBlockAlreadyExists,

    [JsonStringEnumMemberName("community_follower_already_exists")]
    CommunityFollowerAlreadyExists,

    [JsonStringEnumMemberName("couldnt_update_community_hidden_status")]
    CouldntUpdateCommunityHiddenStatus,

    [JsonStringEnumMemberName("person_block_already_exists")]
    PersonBlockAlreadyExists,

    [JsonStringEnumMemberName("user_already_exists")]
    UserAlreadyExists,

    [JsonStringEnumMemberName("token_not_found")]
    TokenNotFound,

    [JsonStringEnumMemberName("couldnt_like_post")]
    CouldntLikePost,

    [JsonStringEnumMemberName("couldnt_save_post")]
    CouldntSavePost,

    [JsonStringEnumMemberName("couldnt_mark_post_as_read")]
    CouldntMarkPostAsRead,

    [JsonStringEnumMemberName("couldnt_hide_post")]
    CouldntHidePost,

    [JsonStringEnumMemberName("couldnt_update_community")]
    CouldntUpdateCommunity,

    [JsonStringEnumMemberName("couldnt_update_replies")]
    CouldntUpdateReplies,

    [JsonStringEnumMemberName("couldnt_update_person_mentions")]
    CouldntUpdatePersonMentions,

    [JsonStringEnumMemberName("post_title_too_long")]
    PostTitleTooLong,

    [JsonStringEnumMemberName("couldnt_create_post")]
    CouldntCreatePost,

    [JsonStringEnumMemberName("couldnt_create_private_message")]
    CouldntCreatePrivateMessage,

    [JsonStringEnumMemberName("couldnt_update_private")]
    CouldntUpdatePrivate,

    [JsonStringEnumMemberName("system_err_login")]
    SystemErrLogin,

    [JsonStringEnumMemberName("couldnt_set_all_registrations_accepted")]
    CouldntSetAllRegistrationsAccepted,

    [JsonStringEnumMemberName("couldnt_set_all_email_verified")]
    CouldntSetAllEmailVerified,

    [JsonStringEnumMemberName("banned")]
    Banned,

    [JsonStringEnumMemberName("blocked_url")]
    BlockedUrl,

    [JsonStringEnumMemberName("couldnt_get_comments")]
    CouldntGetComments,

    [JsonStringEnumMemberName("couldnt_get_posts")]
    CouldntGetPosts,

    [JsonStringEnumMemberName("invalid_url")]
    InvalidUrl,

    [JsonStringEnumMemberName("email_send_failed")]
    EmailSendFailed,

    [JsonStringEnumMemberName("slurs")]
    Slurs,

    [JsonStringEnumMemberName("couldnt_find_object")]
    CouldntFindObject,

    [JsonStringEnumMemberName("registration_denied")]
    RegistrationDenied,

    [JsonStringEnumMemberName("federation_disabled")]
    FederationDisabled,

    [JsonStringEnumMemberName("domain_blocked")]
    DomainBlocked,

    [JsonStringEnumMemberName("domain_not_in_allow_list")]
    DomainNotInAllowList,

    [JsonStringEnumMemberName("federation_disabled_by_strict_allow_list")]
    FederationDisabledByStrictAllowList,

    [JsonStringEnumMemberName("site_name_required")]
    SiteNameRequired,

    [JsonStringEnumMemberName("site_name_length_overflow")]
    SiteNameLengthOverflow,

    [JsonStringEnumMemberName("permissive_regex")]
    PermissiveRegex,

    [JsonStringEnumMemberName("invalid_regex")]
    InvalidRegex,

    [JsonStringEnumMemberName("captcha_incorrect")]
    CaptchaIncorrect,

    [JsonStringEnumMemberName("couldnt_create_audio_captcha")]
    CouldntCreateAudioCaptcha,

    [JsonStringEnumMemberName("invalid_url_scheme")]
    InvalidUrlScheme,

    [JsonStringEnumMemberName("couldnt_send_webmention")]
    CouldntSendWebmention,

    [JsonStringEnumMemberName("contradicting_filters")]
    ContradictingFilters,

    [JsonStringEnumMemberName("instance_block_already_exists")]
    InstanceBlockAlreadyExists,

    [JsonStringEnumMemberName("too_many_items")]
    TooManyItems,

    [JsonStringEnumMemberName("community_has_no_followers")]
    CommunityHasNoFollowers,

    [JsonStringEnumMemberName("ban_expiration_in_past")]
    BanExpirationInPast,

    [JsonStringEnumMemberName("invalid_unix_time")]
    InvalidUnixTime,

    [JsonStringEnumMemberName("invalid_bot_action")]
    InvalidBotAction,

    [JsonStringEnumMemberName("cant_block_local_instance")]
    CantBlockLocalInstance,

    [JsonStringEnumMemberName("url_without_domain")]
    UrlWithoutDomain,

    [JsonStringEnumMemberName("inbox_timeout")]
    InboxTimeout,

    [JsonStringEnumMemberName("unknown")]
    Unknown,

    [JsonStringEnumMemberName("cant_delete_site")]
    CantDeleteSite,

    [JsonStringEnumMemberName("url_length_overflow")]
    UrlLengthOverflow
}
