// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ListCommentLikesResponse
{
    [JsonPropertyName("comment_likes")]
    [RequiredProperty]
    public List<VoteView> CommentLikes { get; set; } = null!;
}
