// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ListPostReports : IPaginatedResult
{
    [JsonPropertyName("page")]
    public long? Page { get; set; }

    [JsonPropertyName("limit")]
    public long? Limit { get; set; }

    [JsonPropertyName("unresolved_only")]
    public bool? UnresolvedOnly { get; set; }

    [JsonPropertyName("community_id")]
    public long? CommunityId { get; set; }

    [JsonPropertyName("post_id")]
    public long? PostId { get; set; }
}
