// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalSiteRateLimit
{
    [JsonPropertyName("local_site_id")]
    [RequiredProperty]
    public long LocalSiteId { get; set; }

    [JsonPropertyName("message")]
    [RequiredProperty]
    public long Message { get; set; }

    [JsonPropertyName("message_per_second")]
    [RequiredProperty]
    public long MessagePerSecond { get; set; }

    [JsonPropertyName("post")]
    [RequiredProperty]
    public long Post { get; set; }

    [JsonPropertyName("post_per_second")]
    [RequiredProperty]
    public long PostPerSecond { get; set; }

    [JsonPropertyName("register")]
    [RequiredProperty]
    public long Register { get; set; }

    [JsonPropertyName("register_per_second")]
    [RequiredProperty]
    public long RegisterPerSecond { get; set; }

    [JsonPropertyName("image")]
    [RequiredProperty]
    public long Image { get; set; }

    [JsonPropertyName("image_per_second")]
    [RequiredProperty]
    public long ImagePerSecond { get; set; }

    [JsonPropertyName("comment")]
    [RequiredProperty]
    public long Comment { get; set; }

    [JsonPropertyName("comment_per_second")]
    [RequiredProperty]
    public long CommentPerSecond { get; set; }

    [JsonPropertyName("search")]
    [RequiredProperty]
    public long Search { get; set; }

    [JsonPropertyName("search_per_second")]
    [RequiredProperty]
    public long SearchPerSecond { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("import_user_settings")]
    [RequiredProperty]
    public long ImportUserSettings { get; set; }

    [JsonPropertyName("import_user_settings_per_second")]
    [RequiredProperty]
    public long ImportUserSettingsPerSecond { get; set; }
}
