// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalImage
{
    [JsonPropertyName("local_user_id")]
    public long? LocalUserId { get; set; }

    [JsonPropertyName("pictrs_alias")]
    [RequiredProperty]
    public string PictrsAlias { get; set; } = null!;

    [JsonPropertyName("pictrs_delete_token")]
    [RequiredProperty]
    public string PictrsDeleteToken { get; set; } = null!;

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;
}
