// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalUserVoteDisplayMode
{
    [JsonPropertyName("local_user_id")]
    [RequiredProperty]
    public long LocalUserId { get; set; }

    [JsonPropertyName("score")]
    [RequiredProperty]
    public bool Score { get; set; }

    [JsonPropertyName("upvotes")]
    [RequiredProperty]
    public bool Upvotes { get; set; }

    [JsonPropertyName("downvotes")]
    [RequiredProperty]
    public bool Downvotes { get; set; }

    [JsonPropertyName("upvote_percentage")]
    [RequiredProperty]
    public bool UpvotePercentage { get; set; }
}
