// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalUser
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("person_id")]
    [RequiredProperty]
    public long PersonId { get; set; }

    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("show_nsfw")]
    [RequiredProperty]
    public bool ShowNsfw { get; set; }

    [JsonPropertyName("theme")]
    [RequiredProperty]
    public string Theme { get; set; } = null!;

    [JsonPropertyName("default_sort_type")]
    [RequiredProperty]
    public SortType DefaultSortType { get; set; }

    [JsonPropertyName("default_listing_type")]
    [RequiredProperty]
    public ListingType DefaultListingType { get; set; }

    [JsonPropertyName("interface_language")]
    [RequiredProperty]
    public string InterfaceLanguage { get; set; } = null!;

    [JsonPropertyName("show_avatars")]
    [RequiredProperty]
    public bool ShowAvatars { get; set; }

    [JsonPropertyName("send_notifications_to_email")]
    [RequiredProperty]
    public bool SendNotificationsToEmail { get; set; }

    [JsonPropertyName("show_scores")]
    [RequiredProperty]
    public bool ShowScores { get; set; }

    [JsonPropertyName("show_bot_accounts")]
    [RequiredProperty]
    public bool ShowBotAccounts { get; set; }

    [JsonPropertyName("show_read_posts")]
    [RequiredProperty]
    public bool ShowReadPosts { get; set; }

    [JsonPropertyName("email_verified")]
    [RequiredProperty]
    public bool EmailVerified { get; set; }

    [JsonPropertyName("accepted_application")]
    [RequiredProperty]
    public bool AcceptedApplication { get; set; }

    [JsonPropertyName("open_links_in_new_tab")]
    [RequiredProperty]
    public bool OpenLinksInNewTab { get; set; }

    [JsonPropertyName("blur_nsfw")]
    [RequiredProperty]
    public bool BlurNsfw { get; set; }

    [JsonPropertyName("auto_expand")]
    [RequiredProperty]
    public bool AutoExpand { get; set; }

    [JsonPropertyName("infinite_scroll_enabled")]
    [RequiredProperty]
    public bool InfiniteScrollEnabled { get; set; }

    [JsonPropertyName("admin")]
    [RequiredProperty]
    public bool Admin { get; set; }

    [JsonPropertyName("post_listing_mode")]
    [RequiredProperty]
    public PostListingMode PostListingMode { get; set; }

    [JsonPropertyName("totp_2fa_enabled")]
    [RequiredProperty]
    public bool Totp2faEnabled { get; set; }

    [JsonPropertyName("enable_keyboard_navigation")]
    [RequiredProperty]
    public bool EnableKeyboardNavigation { get; set; }

    [JsonPropertyName("enable_animated_images")]
    [RequiredProperty]
    public bool EnableAnimatedImages { get; set; }

    [JsonPropertyName("collapse_bot_comments")]
    [RequiredProperty]
    public bool CollapseBotComments { get; set; }

    [JsonPropertyName("last_donation_notification")]
    [RequiredProperty]
    public string LastDonationNotification { get; set; } = null!;
}
