// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalUserView
{
    [JsonPropertyName("local_user")]
    [RequiredProperty]
    public LocalUser LocalUser { get; set; } = null!;

    [JsonPropertyName("local_user_vote_display_mode")]
    [RequiredProperty]
    public LocalUserVoteDisplayMode LocalUserVoteDisplayMode { get; set; } = null!;

    [JsonPropertyName("person")]
    [RequiredProperty]
    public Person Person { get; set; } = null!;

    [JsonPropertyName("counts")]
    [RequiredProperty]
    public PersonAggregates Counts { get; set; } = null!;
}
