// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalSite
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("site_id")]
    [RequiredProperty]
    public long SiteId { get; set; }

    [JsonPropertyName("site_setup")]
    [RequiredProperty]
    public bool SiteSetup { get; set; }

    [JsonPropertyName("enable_downvotes")]
    [RequiredProperty]
    public bool EnableDownvotes { get; set; }

    [JsonPropertyName("enable_nsfw")]
    [RequiredProperty]
    public bool EnableNsfw { get; set; }

    [JsonPropertyName("community_creation_admin_only")]
    [RequiredProperty]
    public bool CommunityCreationAdminOnly { get; set; }

    [JsonPropertyName("require_email_verification")]
    [RequiredProperty]
    public bool RequireEmailVerification { get; set; }

    [JsonPropertyName("application_question")]
    public string? ApplicationQuestion { get; set; }

    [JsonPropertyName("private_instance")]
    [RequiredProperty]
    public bool PrivateInstance { get; set; }

    [JsonPropertyName("default_theme")]
    [RequiredProperty]
    public string DefaultTheme { get; set; } = null!;

    [JsonPropertyName("default_post_listing_type")]
    [RequiredProperty]
    public ListingType DefaultPostListingType { get; set; }

    [JsonPropertyName("legal_information")]
    public string? LegalInformation { get; set; }

    [JsonPropertyName("hide_modlog_mod_names")]
    [RequiredProperty]
    public bool HideModlogModNames { get; set; }

    [JsonPropertyName("application_email_admins")]
    [RequiredProperty]
    public bool ApplicationEmailAdmins { get; set; }

    [JsonPropertyName("slur_filter_regex")]
    public string? SlurFilterRegex { get; set; }

    [JsonPropertyName("actor_name_max_length")]
    [RequiredProperty]
    public long ActorNameMaxLength { get; set; }

    [JsonPropertyName("federation_enabled")]
    [RequiredProperty]
    public bool FederationEnabled { get; set; }

    [JsonPropertyName("captcha_enabled")]
    [RequiredProperty]
    public bool CaptchaEnabled { get; set; }

    [JsonPropertyName("captcha_difficulty")]
    [RequiredProperty]
    public string CaptchaDifficulty { get; set; } = null!;

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("registration_mode")]
    [RequiredProperty]
    public RegistrationMode RegistrationMode { get; set; }

    [JsonPropertyName("reports_email_admins")]
    [RequiredProperty]
    public bool ReportsEmailAdmins { get; set; }

    [JsonPropertyName("federation_signed_fetch")]
    [RequiredProperty]
    public bool FederationSignedFetch { get; set; }

    [JsonPropertyName("default_post_listing_mode")]
    [RequiredProperty]
    public PostListingMode DefaultPostListingMode { get; set; }

    [JsonPropertyName("default_sort_type")]
    [RequiredProperty]
    public SortType DefaultSortType { get; set; }
}
