// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LocalImageView
{
    [JsonPropertyName("local_image")]
    [RequiredProperty]
    public LocalImage LocalImage { get; set; } = null!;

    [JsonPropertyName("person")]
    [RequiredProperty]
    public Person Person { get; set; } = null!;
}
