// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LoginResponse
{
    [JsonPropertyName("jwt")]
    public string? Jwt { get; set; }

    [JsonPropertyName("registration_created")]
    [RequiredProperty]
    public bool RegistrationCreated { get; set; }

    [JsonPropertyName("verify_email_sent")]
    [RequiredProperty]
    public bool VerifyEmailSent { get; set; }
}
