// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Login
{
    [JsonPropertyName("username_or_email")]
    [RequiredProperty]
    public string UsernameOrEmail { get; set; } = null!;

    [JsonPropertyName("password")]
    [RequiredProperty]
    public string Password { get; set; } = null!;

    [JsonPropertyName("totp_2fa_token")]
    public string? Totp2faToken { get; set; }
}
