// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class LoginToken
{
    [JsonPropertyName("user_id")]
    [RequiredProperty]
    public long UserId { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("ip")]
    public string? Ip { get; set; }

    [JsonPropertyName("user_agent")]
    public string? UserAgent { get; set; }
}
