// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class MarkPersonMentionAsRead
{
    [JsonPropertyName("person_mention_id")]
    [RequiredProperty]
    public long PersonMentionId { get; set; }

    [JsonPropertyName("read")]
    [RequiredProperty]
    public bool Read { get; set; }
}
