// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModAddCommunityView
{
    [JsonPropertyName("mod_add_community")]
    [RequiredProperty]
    public ModAddCommunity ModAddCommunity { get; set; } = null!;

    [JsonPropertyName("moderator")]
    public Person? Moderator { get; set; }

    [JsonPropertyName("community")]
    [RequiredProperty]
    public Community Community { get; set; } = null!;

    [JsonPropertyName("modded_person")]
    [RequiredProperty]
    public Person ModdedPerson { get; set; } = null!;
}
