// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModAdd
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("mod_person_id")]
    [RequiredProperty]
    public long ModPersonId { get; set; }

    [JsonPropertyName("other_person_id")]
    [RequiredProperty]
    public long OtherPersonId { get; set; }

    [JsonPropertyName("removed")]
    [RequiredProperty]
    public bool Removed { get; set; }

    [JsonPropertyName("when_")]
    [RequiredProperty]
    public string When { get; set; } = null!;
}
