// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModAddView
{
    [JsonPropertyName("mod_add")]
    [RequiredProperty]
    public ModAdd ModAdd { get; set; } = null!;

    [JsonPropertyName("moderator")]
    public Person? Moderator { get; set; }

    [JsonPropertyName("modded_person")]
    [RequiredProperty]
    public Person ModdedPerson { get; set; } = null!;
}
