// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModBanView
{
    [JsonPropertyName("mod_ban")]
    [RequiredProperty]
    public ModBan ModBan { get; set; } = null!;

    [JsonPropertyName("moderator")]
    public Person? Moderator { get; set; }

    [JsonPropertyName("banned_person")]
    [RequiredProperty]
    public Person BannedPerson { get; set; } = null!;
}
