// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModFeaturePost
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("mod_person_id")]
    [RequiredProperty]
    public long ModPersonId { get; set; }

    [JsonPropertyName("post_id")]
    [RequiredProperty]
    public long PostId { get; set; }

    [JsonPropertyName("featured")]
    [RequiredProperty]
    public bool Featured { get; set; }

    [JsonPropertyName("when_")]
    [RequiredProperty]
    public string When { get; set; } = null!;

    [JsonPropertyName("is_featured_community")]
    [RequiredProperty]
    public bool IsFeaturedCommunity { get; set; }
}
