// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModHideCommunityView
{
    [JsonPropertyName("mod_hide_community")]
    [RequiredProperty]
    public ModHideCommunity ModHideCommunity { get; set; } = null!;

    [JsonPropertyName("admin")]
    public Person? Admin { get; set; }

    [JsonPropertyName("community")]
    [RequiredProperty]
    public Community Community { get; set; } = null!;
}
