// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ModlogActionType
{
    [JsonStringEnumMemberName("All")]
    All,

    [JsonStringEnumMemberName("ModRemovePost")]
    ModRemovePost,

    [JsonStringEnumMemberName("ModLockPost")]
    ModLockPost,

    [JsonStringEnumMemberName("ModFeaturePost")]
    ModFeaturePost,

    [JsonStringEnumMemberName("ModRemoveComment")]
    ModRemoveComment,

    [JsonStringEnumMemberName("ModRemoveCommunity")]
    ModRemoveCommunity,

    [JsonStringEnumMemberName("ModBanFromCommunity")]
    ModBanFromCommunity,

    [JsonStringEnumMemberName("ModAddCommunity")]
    ModAddCommunity,

    [JsonStringEnumMemberName("ModTransferCommunity")]
    ModTransferCommunity,

    [JsonStringEnumMemberName("ModAdd")]
    ModAdd,

    [JsonStringEnumMemberName("ModBan")]
    ModBan,

    [JsonStringEnumMemberName("ModHideCommunity")]
    ModHideCommunity,

    [JsonStringEnumMemberName("AdminPurgePerson")]
    AdminPurgePerson,

    [JsonStringEnumMemberName("AdminPurgeCommunity")]
    AdminPurgeCommunity,

    [JsonStringEnumMemberName("AdminPurgePost")]
    AdminPurgePost,

    [JsonStringEnumMemberName("AdminPurgeComment")]
    AdminPurgeComment
}
