// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModLockPostView
{
    [JsonPropertyName("mod_lock_post")]
    [RequiredProperty]
    public ModLockPost ModLockPost { get; set; } = null!;

    [JsonPropertyName("moderator")]
    public Person? Moderator { get; set; }

    [JsonPropertyName("post")]
    [RequiredProperty]
    public Post Post { get; set; } = null!;

    [JsonPropertyName("community")]
    [RequiredProperty]
    public Community Community { get; set; } = null!;
}
