// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ModlogListParams : IPaginatedResult
{
    [JsonPropertyName("community_id")]
    public long? CommunityId { get; set; }

    [JsonPropertyName("mod_person_id")]
    public long? ModPersonId { get; set; }

    [JsonPropertyName("other_person_id")]
    public long? OtherPersonId { get; set; }

    [JsonPropertyName("post_id")]
    public long? PostId { get; set; }

    [JsonPropertyName("comment_id")]
    public long? CommentId { get; set; }

    [JsonPropertyName("page")]
    public long? Page { get; set; }

    [JsonPropertyName("limit")]
    public long? Limit { get; set; }

    [JsonPropertyName("hide_modlog_names")]
    [RequiredProperty]
    public bool HideModlogNames { get; set; }
}
