// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class MyUserInfo
{
    [JsonPropertyName("local_user_view")]
    [RequiredProperty]
    public LocalUserView LocalUserView { get; set; } = null!;

    [JsonPropertyName("follows")]
    [RequiredProperty]
    public List<CommunityFollowerView> Follows { get; set; } = null!;

    [JsonPropertyName("moderates")]
    [RequiredProperty]
    public List<CommunityModeratorView> Moderates { get; set; } = null!;

    [JsonPropertyName("community_blocks")]
    [RequiredProperty]
    public List<CommunityBlockView> CommunityBlocks { get; set; } = null!;

    [JsonPropertyName("instance_blocks")]
    [RequiredProperty]
    public List<InstanceBlockView> InstanceBlocks { get; set; } = null!;

    [JsonPropertyName("person_blocks")]
    [RequiredProperty]
    public List<PersonBlockView> PersonBlocks { get; set; } = null!;

    [JsonPropertyName("discussion_languages")]
    [RequiredProperty]
    public List<long> DiscussionLanguages { get; set; } = null!;
}
