// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PasswordChangeAfterReset
{
    [JsonPropertyName("token")]
    [RequiredProperty]
    public string Token { get; set; } = null!;

    [JsonPropertyName("password")]
    [RequiredProperty]
    public string Password { get; set; } = null!;

    [JsonPropertyName("password_verify")]
    [RequiredProperty]
    public string PasswordVerify { get; set; } = null!;
}
