// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PersonMention
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("recipient_id")]
    [RequiredProperty]
    public long RecipientId { get; set; }

    [JsonPropertyName("comment_id")]
    [RequiredProperty]
    public long CommentId { get; set; }

    [JsonPropertyName("read")]
    [RequiredProperty]
    public bool Read { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;
}
