// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Person
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("name")]
    [RequiredProperty]
    public string Name { get; set; } = null!;

    [JsonPropertyName("display_name")]
    public string? DisplayName { get; set; }

    [JsonPropertyName("avatar")]
    public string? Avatar { get; set; }

    [JsonPropertyName("banned")]
    [RequiredProperty]
    public bool Banned { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("actor_id")]
    [RequiredProperty]
    public string ActorId { get; set; } = null!;

    [JsonPropertyName("bio")]
    public string? Bio { get; set; }

    [JsonPropertyName("local")]
    [RequiredProperty]
    public bool Local { get; set; }

    [JsonPropertyName("banner")]
    public string? Banner { get; set; }

    [JsonPropertyName("deleted")]
    [RequiredProperty]
    public bool Deleted { get; set; }

    [JsonPropertyName("matrix_user_id")]
    public string? MatrixUserId { get; set; }

    [JsonPropertyName("bot_account")]
    [RequiredProperty]
    public bool BotAccount { get; set; }

    [JsonPropertyName("ban_expires")]
    public string? BanExpires { get; set; }

    [JsonPropertyName("instance_id")]
    [RequiredProperty]
    public long InstanceId { get; set; }
}
