// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PersonAggregates
{
    [JsonPropertyName("person_id")]
    [RequiredProperty]
    public long PersonId { get; set; }

    [JsonPropertyName("post_count")]
    [RequiredProperty]
    public long PostCount { get; set; }

    [JsonPropertyName("comment_count")]
    [RequiredProperty]
    public long CommentCount { get; set; }
}
