// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PersonView
{
    [JsonPropertyName("person")]
    [RequiredProperty]
    public Person Person { get; set; } = null!;

    [JsonPropertyName("counts")]
    [RequiredProperty]
    public PersonAggregates Counts { get; set; } = null!;

    [JsonPropertyName("is_admin")]
    [RequiredProperty]
    public bool IsAdmin { get; set; }
}
