// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Post
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("name")]
    [RequiredProperty]
    public string Name { get; set; } = null!;

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("body")]
    public string? Body { get; set; }

    [JsonPropertyName("creator_id")]
    [RequiredProperty]
    public long CreatorId { get; set; }

    [JsonPropertyName("community_id")]
    [RequiredProperty]
    public long CommunityId { get; set; }

    [JsonPropertyName("removed")]
    [RequiredProperty]
    public bool Removed { get; set; }

    [JsonPropertyName("locked")]
    [RequiredProperty]
    public bool Locked { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("deleted")]
    [RequiredProperty]
    public bool Deleted { get; set; }

    [JsonPropertyName("nsfw")]
    [RequiredProperty]
    public bool Nsfw { get; set; }

    [JsonPropertyName("embed_title")]
    public string? EmbedTitle { get; set; }

    [JsonPropertyName("embed_description")]
    public string? EmbedDescription { get; set; }

    [JsonPropertyName("thumbnail_url")]
    public string? ThumbnailUrl { get; set; }

    [JsonPropertyName("ap_id")]
    [RequiredProperty]
    public string ApId { get; set; } = null!;

    [JsonPropertyName("local")]
    [RequiredProperty]
    public bool Local { get; set; }

    [JsonPropertyName("embed_video_url")]
    public string? EmbedVideoUrl { get; set; }

    [JsonPropertyName("language_id")]
    [RequiredProperty]
    public long LanguageId { get; set; }

    [JsonPropertyName("featured_community")]
    [RequiredProperty]
    public bool FeaturedCommunity { get; set; }

    [JsonPropertyName("featured_local")]
    [RequiredProperty]
    public bool FeaturedLocal { get; set; }

    [JsonPropertyName("url_content_type")]
    public string? UrlContentType { get; set; }

    [JsonPropertyName("alt_text")]
    public string? AltText { get; set; }
}
