// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PostReportView
{
    [JsonPropertyName("post_report")]
    [RequiredProperty]
    public PostReport PostReport { get; set; } = null!;

    [JsonPropertyName("post")]
    [RequiredProperty]
    public Post Post { get; set; } = null!;

    [JsonPropertyName("community")]
    [RequiredProperty]
    public Community Community { get; set; } = null!;

    [JsonPropertyName("creator")]
    [RequiredProperty]
    public Person Creator { get; set; } = null!;

    [JsonPropertyName("post_creator")]
    [RequiredProperty]
    public Person PostCreator { get; set; } = null!;

    [JsonPropertyName("creator_banned_from_community")]
    [RequiredProperty]
    public bool CreatorBannedFromCommunity { get; set; }

    [JsonPropertyName("creator_is_moderator")]
    [RequiredProperty]
    public bool CreatorIsModerator { get; set; }

    [JsonPropertyName("creator_is_admin")]
    [RequiredProperty]
    public bool CreatorIsAdmin { get; set; }

    [JsonPropertyName("subscribed")]
    [RequiredProperty]
    public SubscribedType Subscribed { get; set; }

    [JsonPropertyName("saved")]
    [RequiredProperty]
    public bool Saved { get; set; }

    [JsonPropertyName("read")]
    [RequiredProperty]
    public bool Read { get; set; }

    [JsonPropertyName("hidden")]
    [RequiredProperty]
    public bool Hidden { get; set; }

    [JsonPropertyName("creator_blocked")]
    [RequiredProperty]
    public bool CreatorBlocked { get; set; }

    [JsonPropertyName("my_vote")]
    public long? MyVote { get; set; }

    [JsonPropertyName("unread_comments")]
    [RequiredProperty]
    public long UnreadComments { get; set; }

    [JsonPropertyName("counts")]
    [RequiredProperty]
    public PostAggregates Counts { get; set; } = null!;

    [JsonPropertyName("resolver")]
    public Person? Resolver { get; set; }
}
