// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PostReport
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("creator_id")]
    [RequiredProperty]
    public long CreatorId { get; set; }

    [JsonPropertyName("post_id")]
    [RequiredProperty]
    public long PostId { get; set; }

    [JsonPropertyName("original_post_name")]
    [RequiredProperty]
    public string OriginalPostName { get; set; } = null!;

    [JsonPropertyName("original_post_url")]
    public string? OriginalPostUrl { get; set; }

    [JsonPropertyName("original_post_body")]
    public string? OriginalPostBody { get; set; }

    [JsonPropertyName("reason")]
    [RequiredProperty]
    public string Reason { get; set; } = null!;

    [JsonPropertyName("resolved")]
    [RequiredProperty]
    public bool Resolved { get; set; }

    [JsonPropertyName("resolver_id")]
    public long? ResolverId { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }
}
