// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PostAggregates
{
    [JsonPropertyName("post_id")]
    [RequiredProperty]
    public long PostId { get; set; }

    [JsonPropertyName("comments")]
    [RequiredProperty]
    public long Comments { get; set; }

    [JsonPropertyName("score")]
    [RequiredProperty]
    public long Score { get; set; }

    [JsonPropertyName("upvotes")]
    [RequiredProperty]
    public long Upvotes { get; set; }

    [JsonPropertyName("downvotes")]
    [RequiredProperty]
    public long Downvotes { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("newest_comment_time")]
    [RequiredProperty]
    public string NewestCommentTime { get; set; } = null!;
}
