// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PrivateMessage
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("creator_id")]
    [RequiredProperty]
    public long CreatorId { get; set; }

    [JsonPropertyName("recipient_id")]
    [RequiredProperty]
    public long RecipientId { get; set; }

    [JsonPropertyName("content")]
    [RequiredProperty]
    public string Content { get; set; } = null!;

    [JsonPropertyName("deleted")]
    [RequiredProperty]
    public bool Deleted { get; set; }

    [JsonPropertyName("read")]
    [RequiredProperty]
    public bool Read { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("ap_id")]
    [RequiredProperty]
    public string ApId { get; set; } = null!;

    [JsonPropertyName("local")]
    [RequiredProperty]
    public bool Local { get; set; }
}
