// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PrivateMessageView
{
    [JsonPropertyName("private_message")]
    [RequiredProperty]
    public PrivateMessage PrivateMessage { get; set; } = null!;

    [JsonPropertyName("creator")]
    [RequiredProperty]
    public Person Creator { get; set; } = null!;

    [JsonPropertyName("recipient")]
    [RequiredProperty]
    public Person Recipient { get; set; } = null!;
}
