// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class PrivateMessageResponse
{
    [JsonPropertyName("private_message_view")]
    [RequiredProperty]
    public PrivateMessageView PrivateMessageView { get; set; } = null!;
}
