// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ReadableFederationState
{
    [JsonPropertyName("instance_id")]
    [RequiredProperty]
    public long InstanceId { get; set; }

    [JsonPropertyName("last_successful_id")]
    public long? LastSuccessfulId { get; set; }

    [JsonPropertyName("last_successful_published_time")]
    public string? LastSuccessfulPublishedTime { get; set; }

    [JsonPropertyName("fail_count")]
    [RequiredProperty]
    public long FailCount { get; set; }

    [JsonPropertyName("last_retry")]
    public string? LastRetry { get; set; }

    [JsonPropertyName("next_retry")]
    public string? NextRetry { get; set; }
}
