// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Register
{
    [JsonPropertyName("username")]
    [RequiredProperty]
    public string Username { get; set; } = null!;

    [JsonPropertyName("password")]
    [RequiredProperty]
    public string Password { get; set; } = null!;

    [JsonPropertyName("password_verify")]
    [RequiredProperty]
    public string PasswordVerify { get; set; } = null!;

    [JsonPropertyName("show_nsfw")]
    public bool? ShowNsfw { get; set; }

    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("captcha_uuid")]
    public string? CaptchaUuid { get; set; }

    [JsonPropertyName("captcha_answer")]
    public string? CaptchaAnswer { get; set; }

    [JsonPropertyName("honeypot")]
    public string? Honeypot { get; set; }

    [JsonPropertyName("answer")]
    public string? Answer { get; set; }
}
