// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class RegistrationApplicationView
{
    [JsonPropertyName("registration_application")]
    [RequiredProperty]
    public RegistrationApplication RegistrationApplication { get; set; } = null!;

    [JsonPropertyName("creator_local_user")]
    [RequiredProperty]
    public LocalUser CreatorLocalUser { get; set; } = null!;

    [JsonPropertyName("creator")]
    [RequiredProperty]
    public Person Creator { get; set; } = null!;

    [JsonPropertyName("admin")]
    public Person? Admin { get; set; }
}
