// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class RegistrationApplication
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("local_user_id")]
    [RequiredProperty]
    public long LocalUserId { get; set; }

    [JsonPropertyName("answer")]
    [RequiredProperty]
    public string Answer { get; set; } = null!;

    [JsonPropertyName("admin_id")]
    public long? AdminId { get; set; }

    [JsonPropertyName("deny_reason")]
    public string? DenyReason { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;
}
