// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class RemoveComment
{
    [JsonPropertyName("comment_id")]
    [RequiredProperty]
    public long CommentId { get; set; }

    [JsonPropertyName("removed")]
    [RequiredProperty]
    public bool Removed { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }
}
