// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class ResolveObjectResponse
{
    [JsonPropertyName("comment")]
    public CommentView? Comment { get; set; }

    [JsonPropertyName("post")]
    public PostView? Post { get; set; }

    [JsonPropertyName("community")]
    public CommunityView? Community { get; set; }

    [JsonPropertyName("person")]
    public PersonView? Person { get; set; }
}
