// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class SaveUserSettings
{
    [JsonPropertyName("show_nsfw")]
    public bool? ShowNsfw { get; set; }

    [JsonPropertyName("blur_nsfw")]
    public bool? BlurNsfw { get; set; }

    [JsonPropertyName("auto_expand")]
    public bool? AutoExpand { get; set; }

    [JsonPropertyName("theme")]
    public string? Theme { get; set; }

    [JsonPropertyName("default_sort_type")]
    public SortType? DefaultSortType { get; set; }

    [JsonPropertyName("default_listing_type")]
    public ListingType? DefaultListingType { get; set; }

    [JsonPropertyName("interface_language")]
    public string? InterfaceLanguage { get; set; }

    [JsonPropertyName("avatar")]
    public string? Avatar { get; set; }

    [JsonPropertyName("banner")]
    public string? Banner { get; set; }

    [JsonPropertyName("display_name")]
    public string? DisplayName { get; set; }

    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("bio")]
    public string? Bio { get; set; }

    [JsonPropertyName("matrix_user_id")]
    public string? MatrixUserId { get; set; }

    [JsonPropertyName("show_avatars")]
    public bool? ShowAvatars { get; set; }

    [JsonPropertyName("send_notifications_to_email")]
    public bool? SendNotificationsToEmail { get; set; }

    [JsonPropertyName("bot_account")]
    public bool? BotAccount { get; set; }

    [JsonPropertyName("show_bot_accounts")]
    public bool? ShowBotAccounts { get; set; }

    [JsonPropertyName("show_read_posts")]
    public bool? ShowReadPosts { get; set; }

    [JsonPropertyName("discussion_languages")]
    public List<long>? DiscussionLanguages { get; set; }

    [JsonPropertyName("open_links_in_new_tab")]
    public bool? OpenLinksInNewTab { get; set; }

    [JsonPropertyName("infinite_scroll_enabled")]
    public bool? InfiniteScrollEnabled { get; set; }

    [JsonPropertyName("post_listing_mode")]
    public PostListingMode? PostListingMode { get; set; }

    [JsonPropertyName("enable_keyboard_navigation")]
    public bool? EnableKeyboardNavigation { get; set; }

    [JsonPropertyName("enable_animated_images")]
    public bool? EnableAnimatedImages { get; set; }

    [JsonPropertyName("collapse_bot_comments")]
    public bool? CollapseBotComments { get; set; }

    [JsonPropertyName("show_scores")]
    public bool? ShowScores { get; set; }

    [JsonPropertyName("show_upvotes")]
    public bool? ShowUpvotes { get; set; }

    [JsonPropertyName("show_downvotes")]
    public bool? ShowDownvotes { get; set; }

    [JsonPropertyName("show_upvote_percentage")]
    public bool? ShowUpvotePercentage { get; set; }
}
