// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class SearchResponse
{
    [JsonPropertyName("type_")]
    [RequiredProperty]
    public SearchType Type { get; set; }

    [JsonPropertyName("comments")]
    [RequiredProperty]
    public List<CommentView> Comments { get; set; } = null!;

    [JsonPropertyName("posts")]
    [RequiredProperty]
    public List<PostView> Posts { get; set; } = null!;

    [JsonPropertyName("communities")]
    [RequiredProperty]
    public List<CommunityView> Communities { get; set; } = null!;

    [JsonPropertyName("users")]
    [RequiredProperty]
    public List<PersonView> Users { get; set; } = null!;
}
