// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Search : IPaginatedResult
{
    [JsonPropertyName("q")]
    [RequiredProperty]
    public string Q { get; set; } = null!;

    [JsonPropertyName("community_id")]
    public long? CommunityId { get; set; }

    [JsonPropertyName("community_name")]
    public string? CommunityName { get; set; }

    [JsonPropertyName("creator_id")]
    public long? CreatorId { get; set; }

    [JsonPropertyName("type_")]
    public SearchType? Type { get; set; }

    [JsonPropertyName("sort")]
    public SortType? Sort { get; set; }

    [JsonPropertyName("listing_type")]
    public ListingType? ListingType { get; set; }

    [JsonPropertyName("page")]
    public long? Page { get; set; }

    [JsonPropertyName("limit")]
    public long? Limit { get; set; }

    [JsonPropertyName("post_title_only")]
    public bool? PostTitleOnly { get; set; }
}
