// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class SiteResponse
{
    [JsonPropertyName("site_view")]
    [RequiredProperty]
    public SiteView SiteView { get; set; } = null!;

    [JsonPropertyName("taglines")]
    [RequiredProperty]
    public List<Tagline> Taglines { get; set; } = null!;
}
