// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class SiteView
{
    [JsonPropertyName("site")]
    [RequiredProperty]
    public Site Site { get; set; } = null!;

    [JsonPropertyName("local_site")]
    [RequiredProperty]
    public LocalSite LocalSite { get; set; } = null!;

    [JsonPropertyName("local_site_rate_limit")]
    [RequiredProperty]
    public LocalSiteRateLimit LocalSiteRateLimit { get; set; } = null!;

    [JsonPropertyName("counts")]
    [RequiredProperty]
    public SiteAggregates Counts { get; set; } = null!;
}
