// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class Site
{
    [JsonPropertyName("id")]
    [RequiredProperty]
    public long Id { get; set; }

    [JsonPropertyName("name")]
    [RequiredProperty]
    public string Name { get; set; } = null!;

    [JsonPropertyName("sidebar")]
    public string? Sidebar { get; set; }

    [JsonPropertyName("published")]
    [RequiredProperty]
    public string Published { get; set; } = null!;

    [JsonPropertyName("updated")]
    public string? Updated { get; set; }

    [JsonPropertyName("icon")]
    public string? Icon { get; set; }

    [JsonPropertyName("banner")]
    public string? Banner { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("actor_id")]
    [RequiredProperty]
    public string ActorId { get; set; } = null!;

    [JsonPropertyName("last_refreshed_at")]
    [RequiredProperty]
    public string LastRefreshedAt { get; set; } = null!;

    [JsonPropertyName("inbox_url")]
    [RequiredProperty]
    public string InboxUrl { get; set; } = null!;

    [JsonPropertyName("public_key")]
    [RequiredProperty]
    public string PublicKey { get; set; } = null!;

    [JsonPropertyName("instance_id")]
    [RequiredProperty]
    public long InstanceId { get; set; }

    [JsonPropertyName("content_warning")]
    public string? ContentWarning { get; set; }
}
