// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class SiteAggregates
{
    [JsonPropertyName("site_id")]
    [RequiredProperty]
    public long SiteId { get; set; }

    [JsonPropertyName("users")]
    [RequiredProperty]
    public long Users { get; set; }

    [JsonPropertyName("posts")]
    [RequiredProperty]
    public long Posts { get; set; }

    [JsonPropertyName("comments")]
    [RequiredProperty]
    public long Comments { get; set; }

    [JsonPropertyName("communities")]
    [RequiredProperty]
    public long Communities { get; set; }

    [JsonPropertyName("users_active_day")]
    [RequiredProperty]
    public long UsersActiveDay { get; set; }

    [JsonPropertyName("users_active_week")]
    [RequiredProperty]
    public long UsersActiveWeek { get; set; }

    [JsonPropertyName("users_active_month")]
    [RequiredProperty]
    public long UsersActiveMonth { get; set; }

    [JsonPropertyName("users_active_half_year")]
    [RequiredProperty]
    public long UsersActiveHalfYear { get; set; }
}
