// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SortType
{
    [JsonStringEnumMemberName("Active")]
    Active,

    [JsonStringEnumMemberName("Hot")]
    Hot,

    [JsonStringEnumMemberName("New")]
    New,

    [JsonStringEnumMemberName("Old")]
    Old,

    [JsonStringEnumMemberName("TopDay")]
    TopDay,

    [JsonStringEnumMemberName("TopWeek")]
    TopWeek,

    [JsonStringEnumMemberName("TopMonth")]
    TopMonth,

    [JsonStringEnumMemberName("TopYear")]
    TopYear,

    [JsonStringEnumMemberName("TopAll")]
    TopAll,

    [JsonStringEnumMemberName("MostComments")]
    MostComments,

    [JsonStringEnumMemberName("NewComments")]
    NewComments,

    [JsonStringEnumMemberName("TopHour")]
    TopHour,

    [JsonStringEnumMemberName("TopSixHour")]
    TopSixHour,

    [JsonStringEnumMemberName("TopTwelveHour")]
    TopTwelveHour,

    [JsonStringEnumMemberName("TopThreeMonths")]
    TopThreeMonths,

    [JsonStringEnumMemberName("TopSixMonths")]
    TopSixMonths,

    [JsonStringEnumMemberName("TopNineMonths")]
    TopNineMonths,

    [JsonStringEnumMemberName("Controversial")]
    Controversial,

    [JsonStringEnumMemberName("Scaled")]
    Scaled
}
