// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class UpdateTotp
{
    [JsonPropertyName("totp_token")]
    [RequiredProperty]
    public string TotpToken { get; set; } = null!;

    [JsonPropertyName("enabled")]
    [RequiredProperty]
    public bool Enabled { get; set; }
}
