// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

public sealed class VoteView
{
    [JsonPropertyName("creator")]
    [RequiredProperty]
    public Person Creator { get; set; } = null!;

    [JsonPropertyName("creator_banned_from_community")]
    [RequiredProperty]
    public bool CreatorBannedFromCommunity { get; set; }

    [JsonPropertyName("score")]
    [RequiredProperty]
    public long Score { get; set; }
}
