#!/usr/bin/env node

import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const sourceDirectory = process.argv[2];
const outputDirectory = resolve(root, "Lemmy.Net/Types");

if (!sourceDirectory) {
  throw new Error("Usage: node utils/generate-models.mjs <lemmy-js-client/src/types>");
}

const files = (await readdir(sourceDirectory))
  .filter(file => file.endsWith(".ts"))
  .sort();
const sources = new Map();
for (const file of files) {
  sources.set(basename(file, ".ts"), await readFile(join(sourceDirectory, file), "utf8"));
}

const primitiveAliases = new Map();
const enumAliases = new Set();
for (const [name, source] of sources) {
  const alias = source.match(/export\s+type\s+\w+\s*=\s*([^;]+);/s)?.[1].trim();
  if (alias && /^(string|number|boolean|bigint)$/.test(alias)) {
    primitiveAliases.set(name, alias);
  }
  if (alias?.includes('"')) enumAliases.add(name);
}

const header = `// <auto-generated />
// Generated from LemmyNet/lemmy-js-client. Run ./utils/generate-models.sh to update.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Lemmy.Net.Types.Attributes;

namespace Lemmy.Net.Types;

`;

function pascalCase(value) {
  const result = value.replace(/_+$/, "")
    .replace(/[^A-Za-z0-9]+(.)/g, (_, character) => character.toUpperCase())
    .replace(/^./, character => character.toUpperCase());
  return /^\d/.test(result) ? `Value${result}` : result;
}

function splitTopLevel(value, separator) {
  const result = [];
  let depth = 0;
  let quoted = false;
  let start = 0;
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    if (character === '"' && value[index - 1] !== "\\") quoted = !quoted;
    if (quoted) continue;
    if ("<([{".includes(character)) depth += 1;
    if (">)]}".includes(character)) depth -= 1;
    if (depth === 0 && character === separator) {
      result.push(value.slice(start, index).trim());
      start = index + 1;
    }
  }
  result.push(value.slice(start).trim());
  return result.filter(Boolean);
}

function resolveAlias(type) {
  const alias = primitiveAliases.get(type);
  return alias ? resolveAlias(alias) : type;
}

function convertType(rawType) {
  let type = rawType.trim().replace(/\s+/g, " ");
  const union = splitTopLevel(type, "|");
  const nullable = union.some(item => item === "null" || item === "undefined");
  if (nullable) {
    type = union.filter(item => item !== "null" && item !== "undefined").join(" | ");
  }

  type = resolveAlias(type);
  let converted;
  const array = type.match(/^(?:Readonly)?Array<(.+)>$/) || type.match(/^(.+)\[\]$/);
  const record = type.match(/^Record<string,\s*(.+)>$/);
  if (array) {
    converted = `List<${convertType(array[1]).type}>`;
  } else if (record) {
    converted = `Dictionary<string, ${convertType(record[1]).type}>`;
  } else {
    converted = ({
      string: "string",
      number: "long",
      bigint: "long",
      boolean: "bool",
      unknown: "JsonElement",
      any: "JsonElement",
      object: "JsonElement",
    })[type] ?? type;
  }

  if (converted.includes(" | ")) converted = "JsonElement";
  return { type: converted, nullable };
}

function generateInterface(name, source) {
  const body = source.match(/export\s+interface\s+\w+\s*{([\s\S]*)}\s*$/)?.[1];
  if (!body) return null;

  const properties = [];
  const propertyPattern = /^\s*(?:readonly\s+)?([A-Za-z_$][\w$]*)\s*(\?)?\s*:\s*([^;]+);/gm;
  for (const match of body.matchAll(propertyPattern)) {
    const [, jsonName, optionalMarker, rawType] = match;
    const converted = convertType(rawType);
    const optional = Boolean(optionalMarker) || converted.nullable;
    const referenceType = !enumAliases.has(converted.type) && (
      converted.type === "string" || converted.type.startsWith("List<") ||
      converted.type.startsWith("Dictionary<") || !/^(long|bool|double|decimal|JsonElement)$/.test(converted.type)
    );
    const nullableSuffix = optional ? "?" : "";
    const initializer = !optional && referenceType ? " = null!;" : "";
    const required = optional ? "" : "    [RequiredProperty]\n";
    properties.push(
      `    [JsonPropertyName("${jsonName}")]\n${required}    public ${converted.type}${nullableSuffix} ${pascalCase(jsonName)} { get; set; }${initializer}`
    );
  }

  if (properties.length === 0 && body.trim()) {
    throw new Error(`Could not parse properties for ${name}`);
  }
  const implementsPagination = properties.some(property => property.includes(" Page { get; set; }")) &&
    properties.some(property => property.includes(" Limit { get; set; }"));
  const interfaces = implementsPagination ? " : IPaginatedResult" : "";
  return `${header}public sealed class ${name}${interfaces}\n{\n${properties.join("\n\n")}\n}\n`;
}

function generateEnum(name, source) {
  const alias = source.match(/export\s+type\s+\w+\s*=\s*([\s\S]+);\s*$/)?.[1];
  if (!alias || !alias.includes('"')) return null;
  const values = [...alias.matchAll(/"([^"]+)"/g)].map(match => match[1]);
  if (values.length === 0) return null;
  const members = values.map(value =>
    `    [JsonStringEnumMemberName("${value}")]\n    ${pascalCase(value)}`
  );
  return `${header}[JsonConverter(typeof(JsonStringEnumConverter))]\npublic enum ${name}\n{\n${members.join(",\n\n")}\n}\n`;
}

await mkdir(outputDirectory, { recursive: true });
const preservedFiles = new Set(["IPaginatedResult.cs", "ImageFile.cs", "UploadImageResponse.cs"]);
for (const file of await readdir(outputDirectory)) {
  if (file.endsWith(".cs") && !preservedFiles.has(file)) {
    await rm(join(outputDirectory, file));
  }
}

let generated = 0;
for (const [name, source] of sources) {
  const output = generateInterface(name, source) ?? generateEnum(name, source);
  if (!output) {
    if (!primitiveAliases.has(name)) throw new Error(`Unsupported declaration in ${name}.ts`);
    continue;
  }
  await writeFile(join(outputDirectory, `${name}.cs`), output);
  generated += 1;
}

console.log(`Generated ${generated} models in ${outputDirectory}`);
